{% set name = "xbudget" %}
{% set version = "0.7.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/x/xbudget/xbudget-{{ version }}.tar.gz
  sha256: 064fb86796879d49bdee7f5887d6d11b8a949402a0a031970a7a0fc1b6be2d29

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy
    - pyyaml
    - xarray
    - xgcm >=0.10.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - xbudget

about:
  home: https://github.com/hdrake/xbudget
  summary: Helper functions and metadata conventions for wrangling finite-volume ocean model budgets
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hdrake
